"""empty message

Revision ID: 72ff26fd3bf9
Revises: 05d02473e89a
Create Date: 2020-03-26 18:14:27.541250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72ff26fd3bf9'
down_revision = '05d02473e89a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('actived_at', sa.DateTime(), nullable=True))
    op.add_column('admins', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'is_active')
    op.drop_column('admins', 'actived_at')
    # ### end Alembic commands ###
