"""empty message

Revision ID: 9c4244c783c1
Revises: b799e80e970d
Create Date: 2020-03-19 10:18:47.402007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c4244c783c1'
down_revision = 'b799e80e970d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_restaurant', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('image_restaurant', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('image_restaurant', 'created')
    op.drop_column('image_restaurant', 'updated')
    op.add_column('images', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('images', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('images', 'created')
    op.drop_column('images', 'updated')
    op.add_column('restaurants', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('restaurants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('restaurants', 'created')
    op.drop_column('restaurants', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.add_column('restaurants', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'created_at')
    op.add_column('images', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.add_column('images', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.add_column('image_restaurant', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.add_column('image_restaurant', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.drop_column('image_restaurant', 'updated_at')
    op.drop_column('image_restaurant', 'created_at')
    # ### end Alembic commands ###
