"""empty message

Revision ID: b799e80e970d
Revises: e4492d7f1555
Create Date: 2020-03-19 10:15:09.159823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b799e80e970d'
down_revision = 'e4492d7f1555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_restaurant', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('image_restaurant', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('images', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('images', sa.Column('updated', sa.DateTime(), nullable=True))
    op.add_column('restaurants', sa.Column('created', sa.DateTime(), nullable=False))
    op.add_column('restaurants', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('restaurants', 'updated')
    op.drop_column('restaurants', 'created')
    op.drop_column('images', 'updated')
    op.drop_column('images', 'created')
    op.drop_column('image_restaurant', 'updated')
    op.drop_column('image_restaurant', 'created')
    # ### end Alembic commands ###
