"""empty message

Revision ID: e4492d7f1555
Revises: aebbc261c61a
Create Date: 2020-03-19 10:13:02.142835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e4492d7f1555'
down_revision = 'aebbc261c61a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_restaurant', 'updated_at')
    op.drop_column('image_restaurant', 'created_at')
    op.drop_column('images', 'updated_at')
    op.drop_column('images', 'created_at')
    op.drop_column('restaurants', 'updated_at')
    op.drop_column('restaurants', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('restaurants', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('images', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('images', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.add_column('image_restaurant', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('image_restaurant', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
